# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ccc2625cb21058a64babc9b6f1f875ce31690f517f2ac382e38efcedb95678f9aae43f2dbeee551c0a5b5261f41ace48f49e85d79073fdea94592284d244a2b2

test:
  secret_key_base: 4b2d1cee4f4309bd871d31a7b87168a435eaa70dd127af5213b466cbeb1a27cdeb01b9ff4147e53dcda09c060d6526ff8aa674e5e55ad355ea9477438250474f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
